Breaking: ES6 Upgrade (fixes: issue/13)
cgkineo/adapt-xAPI pull request #32
Opened 2024-09-26 22:02 UTC by joe-replin

[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* fixes [#13](https://github.com/cgkineo/adapt-xAPI/issues/13)

### Update
* README, Bower & Package updates.
* Old & New Schema files
* All JS files to ES6 standards.
* Removed Favorite & Unfavorite Statement Models.
* Removed Resource Item Statement Model.
* Parent Preffered file with languagePicker and visua11y as children of preferred statement file.

### New
* `_isRestoreEnabled` - If enabled, the course will use xAPI data to restore course progress.
* `_isDebugModeEnabled` - If enabled, the course will continue to generate statements for testing but it will instead post the statement to the console instead of the LRS.
* Config options for `_navbar`, `_visua11y`, & `_trackingErrors`.
* Preferred statement to indicate a user’s chosen course preferences in [adapt-visua11y](https://github.com/cgkineo/adapt-visua11y).
* Interacted statement for tracking buttton interactions within the navbar such as the drawer, [adapt-contrib-pageLevelProgress](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress), & [adapt-visua11y](https://github.com/cgkineo/adapt-visua11y).
* Received statement once a learner is served a notification indicating connectivity issues with the LMS or LRS.
* Accessed statement for tracking resource link selections.
* Viewed statement for tracking glossary term selections.

### Breaking
* Requires 5.19.1 of Adapt due to dependencies.

[//]: # (List appropriate steps for testing if needed)
### Testing
1. Install plug-in to new instance of FW.
2. Additionally install [adapt-visua11y](https://github.com/cgkineo/adapt-visua11y)
3. Set authorization details appropriately in launch.html
4. Disable adapt-contrib-spoor
5. Run down the list, testing each available config option & xAPI statement as listed.

[//]: # (Mention any other dependencies)

2024-09-30 14:23 UTC, oliverfoster commented on js/adapt-kineo-xapi.js
> +import 'libraries/promise-polyfill.min';
these three polyfill lines and their associated files can now be removed.

https://caniuse.com/?search=promise
https://caniuse.com/?search=fetch
https://caniuse.com/?search=url

2024-10-02 17:11 UTC, danielghost commented
Before doing a proper review of this, would it make sense to split this into 2 PRs, one for the ES6 conversion and then once approved a second for the new statement functionality?

It looks like the changes made to AbstractStatementModel is missing from this PR.

2024-10-02 19:58 UTC, joe-replin commented on js/adapt-kineo-xapi.js
> +import 'libraries/promise-polyfill.min';
Much appreciated.

2024-10-04 15:35 UTC, danielghost requested changes
I started making comments as part of a review, but it is too time consuming to highlight these all indivdually, so we can either discuss on a call, or I can update the branch accordingly to switch to APIs within Adapt which weren't present when the orginal plugin was developed, and other ES6 specific amends.

2024-10-04 15:35 UTC, danielghost commented on js/statementModel.js
> +  }
With the way this worked previously these aren't set as `defaults` to be included as `attributes` of the `Backbone.Model`. The `attributes` just consisted of those passed in as follows:
https://github.com/cgkineo/adapt-xAPI/blob/87edb79d0602aa045cdf5e242c5f6c79a68d4170/js/adapt-kineo-xapi.js#L62-L68 

In its current state the logic is a bit mixed and needs addressing.

2024-10-17 19:20 UTC, joe-replin commented on bower.json
> +  "name": "adapt-kineo-xAPI",
Done

2024-10-17 19:22 UTC, joe-replin commented on README.md
> +| \_tracking | Object | `{ _storeQuestionResponses: true, _questionInteractions: true, _assessmentsCompletion: false, _assessmentCompletion: true }` | <ul><li>\_storeQuestionResponses: Restore questi
adjusted.

2024-10-17 19:35 UTC, joe-replin commented on js/adapt-kineo-xapi.js
> +    if (this._config && this._config._isEnabled) {
Done

2024-10-17 19:38 UTC, joe-replin commented on js/adapt-kineo-xapi.js
> +  }
Great callout, thank you.

2024-10-17 19:42 UTC, joe-replin commented on js/adapt-kineo-xapi.js
> +      offlineStorage.initialize(OfflineStorageExtension);
Done

2024-10-17 19:42 UTC, joe-replin commented on js/utils.js
> +    return ISODate + 'T' + ISOTime + ISOOffset;
Done

2024-10-17 19:42 UTC, joe-replin commented on required/launch.html
> +				var auth = "Basic ZDNlNzY5MWVjMzNjYzAzYWU0MmQxNDE0MDY1NzE4ZGUxZGY4Njk3ODo0ODQyMmMyZDA4M2JkZTNjYTc1MzhlNWZkMjQ1ZGQyNGM1MWE5Y2M3";
Done

2024-10-31 19:57 UTC, joe-replin commented on js/launchModel.js
> +      ADL.launch(_.bind(this.onADLLaunchAttempt, this), false);
Completed.

2024-10-31 20:02 UTC, joe-replin commented on js/launchModel.js
> +    });
This was already changed. Opted instead to not rely on usage of underscore and instead converted it to ES6.

2024-10-31 20:12 UTC, joe-replin commented on js/launchModel.js
> +    if (!err) {
Committed refactor with early returns. You were right. This cleaned it up significantly.

2024-10-31 20:22 UTC, joe-replin commented on js/statements/abstractStatementModel.js
> -    const contentRelease = this.get('contentRelease');
Done

2024-10-31 20:24 UTC, joe-replin commented on js/statements/assessmentStatementModel.js
> +    const statement = AbstractStatementModel.prototype.getData.apply(this, arguments);
this was completed

2024-10-31 20:24 UTC, joe-replin commented on js/statements/initializedStatementModel.js
> +    _.extend(extensions, {
This was completed

2024-10-31 20:25 UTC, joe-replin commented on js/errorNotificationModel.js
> +        Adapt.log.error(config.title);
This was done.

2024-12-02 13:02 UTC, oliverfoster approved these changes

2025-03-18 16:31 UTC, oliverfoster commented
@danielghost bump

2025-03-26 22:22 UTC, merged